# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphicsEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphicEditor(object):
    def setupUi(self, GraphicEditor):
        GraphicEditor.setObjectName("GraphicEditor")
        GraphicEditor.resize(640, 480)
        GraphicEditor.setMinimumSize(QtCore.QSize(640, 480))
        GraphicEditor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(GraphicEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.main_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.main_graphicsView.setGeometry(QtCore.QRect(5, 31, 630, 440))
        self.main_graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.main_graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.main_graphicsView.setObjectName("main_graphicsView")
        self.btn_line_type1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_line_type1.setGeometry(QtCore.QRect(5, 3, 25, 25))
        self.btn_line_type1.setObjectName("btn_line_type1")
        self.btn_line_type2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_line_type2.setGeometry(QtCore.QRect(35, 3, 25, 25))
        self.btn_line_type2.setObjectName("btn_line_type2")
        self.btn_line_type3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_line_type3.setGeometry(QtCore.QRect(65, 3, 25, 25))
        self.btn_line_type3.setObjectName("btn_line_type3")
        self.btn_debug_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_debug_next.setGeometry(QtCore.QRect(610, 3, 25, 25))
        self.btn_debug_next.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_debug_next.setIcon(icon)
        self.btn_debug_next.setObjectName("btn_debug_next")
        self.btn_debug_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_debug_start.setGeometry(QtCore.QRect(580, 3, 25, 25))
        self.btn_debug_start.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("bug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_debug_start.setIcon(icon1)
        self.btn_debug_start.setObjectName("btn_debug_start")
        GraphicEditor.setCentralWidget(self.centralwidget)

        self.retranslateUi(GraphicEditor)
        QtCore.QMetaObject.connectSlotsByName(GraphicEditor)

    def retranslateUi(self, GraphicEditor):
        _translate = QtCore.QCoreApplication.translate
        GraphicEditor.setWindowTitle(_translate("GraphicEditor", "GraphicEditor"))
        self.btn_line_type1.setText(_translate("GraphicEditor", "1"))
        self.btn_line_type2.setText(_translate("GraphicEditor", "2"))
        self.btn_line_type3.setText(_translate("GraphicEditor", "3"))
