# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphic_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.main_graphicsView.setGeometry(QtCore.QRect(5, 31, 630, 440))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_graphicsView.sizePolicy().hasHeightForWidth())
        self.main_graphicsView.setSizePolicy(sizePolicy)
        self.main_graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.main_graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.main_graphicsView.setObjectName("main_graphicsView")
        self.btn_line_type1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_line_type1.setGeometry(QtCore.QRect(5, 3, 25, 25))
        self.btn_line_type1.setObjectName("btn_line_type1")
        self.btn_line_type2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_line_type2.setGeometry(QtCore.QRect(35, 3, 25, 25))
        self.btn_line_type2.setObjectName("btn_line_type2")
        self.btn_line_type3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_line_type3.setGeometry(QtCore.QRect(65, 3, 25, 25))
        self.btn_line_type3.setObjectName("btn_line_type3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GraphicEditor"))
        self.btn_line_type1.setText(_translate("MainWindow", "1"))
        self.btn_line_type2.setText(_translate("MainWindow", "2"))
        self.btn_line_type3.setText(_translate("MainWindow", "3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
