# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphicsEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphicEditor(object):
    def setupUi(self, GraphicEditor):
        GraphicEditor.setObjectName("GraphicEditor")
        GraphicEditor.resize(1280, 960)
        GraphicEditor.setMinimumSize(QtCore.QSize(1280, 960))
        GraphicEditor.setMaximumSize(QtCore.QSize(1280, 960))
        self.centralwidget = QtWidgets.QWidget(GraphicEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.main_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.main_graphicsView.setGeometry(QtCore.QRect(5, 31, 1270, 690))
        self.main_graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.main_graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.main_graphicsView.setObjectName("main_graphicsView")
        self.btn_line_type1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_line_type1.setGeometry(QtCore.QRect(60, 3, 25, 25))
        self.btn_line_type1.setObjectName("btn_line_type1")
        self.btn_line_type2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_line_type2.setGeometry(QtCore.QRect(90, 3, 25, 25))
        self.btn_line_type2.setObjectName("btn_line_type2")
        self.btn_line_type3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_line_type3.setGeometry(QtCore.QRect(120, 3, 25, 25))
        self.btn_line_type3.setObjectName("btn_line_type3")
        self.btn_debug_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_debug_next.setGeometry(QtCore.QRect(1240, 3, 25, 25))
        self.btn_debug_next.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_debug_next.setIcon(icon)
        self.btn_debug_next.setObjectName("btn_debug_next")
        self.btn_debug_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_debug_start.setGeometry(QtCore.QRect(1210, 3, 25, 25))
        self.btn_debug_start.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("bug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_debug_start.setIcon(icon1)
        self.btn_debug_start.setObjectName("btn_debug_start")
        self.debug_text_bar = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.debug_text_bar.setGeometry(QtCore.QRect(5, 726, 1270, 229))
        self.debug_text_bar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.debug_text_bar.setReadOnly(True)
        self.debug_text_bar.setObjectName("debug_text_bar")
        self.label_lines = QtWidgets.QLabel(self.centralwidget)
        self.label_lines.setGeometry(QtCore.QRect(10, 3, 67, 25))
        self.label_lines.setObjectName("label_lines")
        self.label_circle = QtWidgets.QLabel(self.centralwidget)
        self.label_circle.setGeometry(QtCore.QRect(180, 3, 67, 25))
        self.label_circle.setObjectName("label_circle")
        self.btn_circle1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_circle1.setGeometry(QtCore.QRect(240, 3, 25, 25))
        self.btn_circle1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_circle1.setIcon(icon2)
        self.btn_circle1.setObjectName("btn_circle1")
        self.btn_ellipse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ellipse.setGeometry(QtCore.QRect(270, 3, 25, 25))
        self.btn_ellipse.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ellipse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ellipse.setIcon(icon3)
        self.btn_ellipse.setObjectName("btn_ellipse")
        GraphicEditor.setCentralWidget(self.centralwidget)

        self.retranslateUi(GraphicEditor)
        QtCore.QMetaObject.connectSlotsByName(GraphicEditor)

    def retranslateUi(self, GraphicEditor):
        _translate = QtCore.QCoreApplication.translate
        GraphicEditor.setWindowTitle(_translate("GraphicEditor", "GraphicEditor"))
        self.btn_line_type1.setText(_translate("GraphicEditor", "1"))
        self.btn_line_type2.setText(_translate("GraphicEditor", "2"))
        self.btn_line_type3.setText(_translate("GraphicEditor", "3"))
        self.label_lines.setText(_translate("GraphicEditor", "Lines:"))
        self.label_circle.setText(_translate("GraphicEditor", "Circle:"))
